jolicode/elastically

.travis.yml
Makefile
README.md

- start the ES Docker container
- run the tests

Add Travis-CI build for all PR / branches

---

src/IndexBuilder.php

purgeOldIndices was not deleting old closed indices.
Use Cluster State API to get the whole list of indices.

Fix the purgeIndex method, the alias API does not list closed index

---

README.md

Add missing documentation about slowDown and speedUp

---

Makefile
README.md
src/Client.php
src/IndexBuilder.php
src/ResultSetBuilder.php
tests/IndexBuilderTest.php

This PR replace https://github.com/jolicode/elastically/pull/5 from @renanbr to add a new commit:
- avoid building the IndexBuilder multiple times 
- move the "pure index name" logic
- change the prefix logic to add a `_` between the prefix and the name
- add tests and documentation
cc #4

Add Prefixed Indexes optional feature

---

src/Indexer.php
src/Messenger/IndexationRequestHandler.php
tests/Messenger/IndexationRequestHandlerTest.php

This is an attempt to implement https://github.com/jolicode/elastically/pull/16#discussion_r370675531

Requeue only failed messages when handling MultipleIndexationRequest

---

src/Transport/HttpClientTransport.php
tests/Transport/HttpClientTransportTest.php

Symfony HttpClient 4xx and 5xx exceptions treatment correction

---

composer.json

Ref #36 
This will be removed when the Serializer is made a required option.

Ref #36, add phpdocumentor/reflection-docblock as explicit deps

---

src/IndexBuilder.php

Fix issue while dealing with prefixed Index. When i try to use prefix index for elastic search purge of indexing is not working. It is taking two time prefixing index name while closing and deleting indexes.

Fix issue while dealing with prefixed Index.

---

src/IndexBuilder.php
src/Indexer.php

- Refactore flush logic which is commonly used to sync operation with Elastic search in batch.

Code refactor.

---

tests/IndexerTest.php

See https://github.com/sebastianbergmann/phpunit/commit/d1199cb2e43a934b51521656be9748f63febe18e

Fixed tests

---

.php_cs
src/Client.php
src/Index.php
src/IndexBuilder.php
src/Indexer.php
src/Messenger/DocumentExchangerInterface.php
src/Messenger/IndexationRequest.php
src/Messenger/IndexationRequestHandler.php
src/Messenger/IndexationRequestInterface.php
src/Messenger/IndexationRequestSpoolSubscriber.php
src/Messenger/MultipleIndexationRequest.php
src/Result.php
src/ResultSetBuilder.php
src/Transport/HttpClientTransport.php
tests/BaseTestCase.php
tests/ClientTest.php
tests/IndexBuilderTest.php
tests/IndexerTest.php
tests/Jane/JaneTest.php
tests/Jane/jane-config.php
tests/Messenger/IndexationRequestHandlerTest.php
tests/Messenger/MemoryQueuingFunctionalTest.php
tests/Messenger/TestControllerFunctionalTest.php
tests/SearchTest.php
tests/Symfony/TestController.php
tests/Symfony/TestKernel.php
tests/Transport/HttpClientTransportTest.php

I took the config from https://github.com/jolicode/starfleet/blob/master/.php_cs

Added PHP-CS-Fixer config + run it

---

src/IndexBuilder.php

This fix all `return` type: methods return instance of Elastically Index, not Elastica One

Fix namespace

---

.github/workflows/ci.yml
README.md

Inspired by https://github.com/elastic/elasticsearch-php/blob/master/.github/workflows/test.yml

Try using the Elastic Github Action + add ES 8

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json
phpstan-baseline.neon
src/IndexBuilder.php

Fix #109 and tests.
PHPStan does not report some of our errors anymore.

Bug #109 Fix tests and Elastica compatibility

---

.github/workflows/ci.yml
CHANGELOG.md
Makefile
README.md

Fix #113.
Add OpenSearch 1 and 2 tests.
Had to duplicate the job because we can't have variables in the `uses` key.

Add OpenSearch in the test matrice

---

README.md

We forgot to switch the badge :fearful:

Replace the TravisCI badge

---

CHANGELOG.md

Prepare release 1.5.3

---

src/IndexBuilder.php

Related to #122 
Using @kftseng suggestion for fix

Fix #122 - unallowed indices for user with opensearch

---

CHANGELOG.md
src/ResultSetBuilder.php

Fix #116 
Using @insekticid suggestion for fix

Throw exception if empty index in ResultSetBuilder #116

---

.github/workflows/ci.yml
CHANGELOG.md
composer.json

Drop support for PHP 7.4

---

.php-cs-fixer.php
CHANGELOG.md
README.md
phpstan-baseline.neon
src/Bridge/Symfony/DependencyInjection/Configuration.php
src/Bridge/Symfony/DependencyInjection/ElasticallyExtension.php
src/Bridge/Symfony/ElasticallyBundle.php
src/Bridge/Symfony/Resources/config/services.php
src/IndexNameMapper.php
src/Mapping/YamlProvider.php
tests/Bridge/Symfony/DependencyInjection/ElasticallyExtensionTest.php
tests/FactoryTest.php

```yaml
elastically:
connections:
default:
client:
host: '%env(ELASTICSEARCH_HOST)%'
mapping_directory: '%kernel.project_dir%/config/elasticsearch'
index_class_mapping:
beers: App\Dto\Beer
```
See the readme for more information

Add a bridge : A bundle for Symfony

---

README.md
src/Bridge/Symfony/DependencyInjection/Configuration.php
src/Bridge/Symfony/DependencyInjection/ElasticallyExtension.php
tests/Bridge/Symfony/DependencyInjection/ElasticallyExtensionTest.php

Fixes #139 
Tested with https://github.com/Korbeil/test-elastically-140. Copy current branch in vendors then run `app:debug` command, you'll have to see the transport in the connection as following:

Invalid transport issue

---

composer.json
src/Bridge/Symfony/Resources/config/services.php

Noticed CI failed recently, so fixed code style

Fix code style

---

composer.json

See https://github.com/symfony/symfony/pull/48718 for details.

fix(tests): Fix compatibility with Doctrine Annotations 2

---

phpstan-baseline.neon
phpstan.neon
src/Bridge/Symfony/DependencyInjection/ElasticallyExtension.php
src/Client.php
src/Index.php
src/IndexBuilder.php
src/IndexNameMapper.php
src/Indexer.php
src/Mapping/MappingProviderInterface.php
src/Mapping/YamlProvider.php
src/Messenger/IndexationRequestHandler.php
src/Messenger/IndexationRequestSpoolSubscriber.php
src/ResultSetBuilder.php
src/Transport/HttpClientTransport.php

Cf https://github.com/jolicode/elastically/pull/160#issuecomment-1593688166

Add missing @throws annotation

---

README.md

:memo: Add a mini-doc about the prefix option
