jolicode/elastically

- src/Client.php
When not present, \DateTime object are normalized by ObjectNormalizer and that does not look good ^^
> Add DateTimeNormalizer in the default Serializer

- README.md
- composer.json
- src/Transport/HttpClientTransport.php
- tests/Transport/HttpClientTransportTest.php
This PR add a new Transport for Elastica, allowing to route all HTTP requests to Symfony HttpClient.
This is nice because it's 100% compatible and you get all the nice things in the HttpClient, for example, debug screen:
> Add HttpClientTransport for Symfony HttpClient on Elastica

- Makefile
- README.md
- composer.json
- phpunit.xml.dist
- src/Client.php
- src/Messenger/IndexationRequest.php
- src/Messenger/IndexationRequestHandler.php
- src/Messenger/IndexationRequestInterface.php
- src/Messenger/IndexationRequestSpoolSubscriber.php
- src/Messenger/MultipleIndexationRequest.php
- tests/ClientTest.php
- tests/Messenger/IndexationRequestHandlerTest.php
- tests/Messenger/MemoryQueuingFunctionalTest.php
- tests/Messenger/TestControllerFunctionalTest.php
- tests/Symfony/TestController.php
- tests/Symfony/TestKernel.php
- tests/Symfony/config.yaml
Symfony Messenger is really simple to use. In this pull request I just add the basic of handling indexation request via Messenger. 
There is a simple DTO, the provided handler must be overwritten to implement the fetchModel method, then I call the proper methods on the Indexer.
I use a very close version of this in production already :yum:
> Add experimental support for Symfony Messenger

- src/IndexBuilder.php
- tests/IndexBuilderTest.php
- tests/configs_analysis/foo_bar_mapping.yaml
- tests/configs_analysis/foo_mapping.yaml
This PR is an attempt to fix #24
With this fix the `IndexBuilder->purgeOldIndices()` will skip purging indices which their suffix isn't a valid date time.
---
To think about: Should it relays only on the index name? Why not track the "public" name and created date in the index metadata?
> Check candidate index name suffix before purge it

- README.md
- src/Messenger/DocumentExchangerInterface.php
- src/Messenger/IndexationRequestHandler.php
- tests/Messenger/IndexationRequestHandlerTest.php
This PR introduces a new interface `DocumentExchangerInterface` that aims to replace the abstract function `IndexationRequestHandler->fetchDocument()`.
> Introduce DocumentExchangerInterface

- .gitignore
- README.md
- composer.json
- tests/Jane/JaneTest.php
- tests/Jane/jane-config.php
- tests/Jane/schema.json
Jane 6.0 fixes #12, which is great news.
This PR adds tests for Jane support by building a schema and using the DTO for Indexing and Search.
> Add tests for Jane JSON Schema 6.x, allow fast DTO In and Out

- README.md
- src/Client.php
- src/IndexBuilder.php
- tests/IndexBuilderTest.php
Built on top of @nicolassing work in https://github.com/jolicode/elastically/pull/19
This add a new "migrate" method allowing to upgrade mapping on live indexes.
> Add the migrate command to upgrade the mapping of existing indexes

- README.md
Hello!  🙂 
Nice bundle!
I was missing the usual `composer require` line for copy & pasting, so I thought I just might add it.
> Add section on how to install

- README.md
kernel.root_dir is deprecated since Symfony 4.2
see https://symfony.com/blog/new-in-symfony-4-2-important-deprecations
> Use kernel.project_dir instead of kernel.root_dir in example

- src/IndexBuilder.php
Hi, we have an use case where we'd like to specify one mapping for multiple indexes (one index per locale).
This change would allow this use case without breaking existing code.
> Add optional fileName parameter to specify an index file name

- CHANGELOG.md
- README.md
- src/Indexer.php
- tests/IndexerTest.php
See #31 
This change allow all kind of query string parameter being added to the Bulk.
> Ref #31 Add bulk query string parameters support

- src/Client.php
- src/Indexer.php
- tests/ClientTest.php
`getIndexNameFromClass` now also working when using an index-prefix configuration.
> Fix getIndexNameFromClass with index prefix

- CHANGELOG.md
- composer.json
- src/Client.php
- src/Index.php
Move all di hacks to the same god object (Client)
> deprecates `Index::getBuilder()` in favor of `Client::getBuilder()`

- .github/workflows/ci.yml
- Makefile
- composer.json
- phpstan.neon
Hi,
I noticed I couldn't run phpstan locally & it would only run in CI, so:
- added phpstan to dev requirements
- created config to share between CI & local runs
- added phpstan in Makefile
> phpstan: allow to run locally & create base config

- .gitignore
This should not be needed anymore, as it's the name of the cache file from PHP-CS-Fixer 2 (see: [upgrade docs](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/UPGRADE-v3.md#rename-of-files))
> Remove legacy PHP-CS-Fixer cache file from .gitignore

- src/IndexNameMapper.php
- src/Indexer.php
- src/Transport/HttpClientTransport.php
- tests/IndexNameMapperTest.php
* getPureIndexName now properly deals with prefixed aliases
* add Tests for getPureIndexName
* add function getMappedIndices to get a list of valid indices
> Fix index name mapper getting pure index name frome alias

- composer.json
Hi
Just a small patch to allow symfony/deprecation-contracts 3.0 (only one commit between 2.5 and 3.0 : https://github.com/symfony/deprecation-contracts/commit/c726b64c1ccfe2896cb7df2e1331c357ad1c8ced)
Signed-off-by: Guillaume Roques <guillaume.roques@gmail.com>
> Allow symfony/deprecation-contracts 3.0

- src/IndexBuilder.php
if using non standardized mapping file naming
```php
//this will work
$indexBuilder->migrate($this->elasticallyClient->getIndex($indexName), [], ['filename' => 'content_mapping.yaml']);
//this works
$index = $indexBuilder->createIndex($indexName, ['filename' => 'content_mapping.yaml']);
```
> Ability to change mapping filename

- composer.json
Without this patch, we get the following error:
```
SYMFONY_REQUIRE=5.4 composer up --prefer-lowest && vendor/bin/simple-phpunit tests/Jane/JaneTest.php
```
```
Testing JoliCode\Elastically\Tests\Jane\JaneTest
Jane (JoliCode\Elastically\Tests\Jane\Jane)
✘ Create index and search with jane object
┐
├ Undefined array key 265
│
╵ /home/gregoire/dev/github.com/jolicode/elastically/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:255
╵ /home/gregoire/dev/github.com/jolicode/elastically/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:209
╵ /home/gregoire/dev/github.com/jolicode/elastically/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:159
╵ /home/gregoire/dev/github.com/jolicode/elastically/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php:51
╵ …
```
> Force nikic/php-parser >= 4.7 because of a strange bug

- src/Bridge/Symfony/DependencyInjection/Configuration.php
This will allow us to do stuff as following: 
```yaml
elastically:
connections:
default:
client: '%env(json:ELASTICSEARCH_CONFIG)%'
mapping_directory: '%kernel.project_dir%/config/elasticsearch'
index_class_mapping:
my-foobar-index:     App\Dto\Foobar
```
With `ELASTICSEARCH_CONFIG='{ "host": "elasticsearch", "port": 9200, "timeout": 4, "persistent": true }'`
> Accept more flexible client configuration by declaring it as variable

- src/Bridge/Symfony/DependencyInjection/ElasticallyExtension.php
- src/Messenger/IndexationRequestHandler.php
This PR will do:
- Fixes #126 by removing the interface and using the new attribute on the Handler
- Fixes #143 by adding the default IndexNameMapper in the Symfony DI in the Bundle
> Fix bundle issues

- composer.json
Changelogs summary:
- phpstan/phpstan updated from 0.12.100 to 1.9.14 major
See changes: https://github.com/phpstan/phpstan/compare/0.12.100...1.9.14
Release notes: https://github.com/phpstan/phpstan/releases/tag/1.9.14
> ci: upgrade PHPStan version

- .php-cs-fixer.php
Perhaps ```PHP82Migration``` would be better.
> ci: change PHP-CS-Fixer config for PHP 8.0

- README.md
The example in the documentation was not working out of the box.
The HttpClientTransport MUST be declared first:
```yaml
JoliCode\Elastically\Transport\HttpClientTransport: ~
```
So I think it's better to comment it out.
Also, what about forcing this transport when using Symfony?!
> doc(symfony): Provide a working example out of the box

- src/Messenger/DocumentExchangerInterface.php
I found a non-needed BC-break in the previous PR https://github.com/jolicode/elastically/pull/150/files#diff-7edcfcd1433b5f1ec1ee43a58328239c89877af7405d35f84ee399eb4bbc251bL14 which was taken from the original https://github.com/jolicode/elastically/pull/149/files#diff-7edcfcd1433b5f1ec1ee43a58328239c89877af7405d35f84ee399eb4bbc251bL14
This PR revert the BC break. I think this require a 1.7.1 release.
@lyrixx @damienalexandre
> Avoid BC-break in DocumentExchangerInterface

- src/Bridge/Symfony/Resources/config/services.php
Hi @lyrixx @damienalexandre,
I recently saw logs in the `app` channel coming from Elastica failure inside vendors.
I think the `app` channel should be reserved to the App folder code.
Doctrine use a `doctrine` channel, Symfony use different channels like `request`, `messenger`, ...
To me elastically should do the same when passing the logger to the elastica client.
This PR fix this by using a custom `elastically` channel for the logs. (I hope I'm doing it right)
> Use specific channel for logs

- .github/workflows/ci.yml
- README.md
- composer.json
- phpunit.xml.dist
- src/Bridge/Symfony/ElasticallyBundle.php
- src/Messenger/IndexationRequestInterface.php
- tests/Messenger/MemoryQueuingFunctionalTest.php
- tests/Messenger/TestControllerFunctionalTest.php
- tests/SearchTest.php
Hi
I've updated the composer.json to allow Symfony ^7.0 and change the CI layout to test it against SF 7 but also 8.3 which release few days ago.
Do you want to keep supporting SF 5.4 (which ended its bug fixes period and entered security fix only https://symfony.com/releases/5.4) ? I can update this PR accordingly
I can also update to only allow 6.4 version instead of all 6.* if needed.
> Update to allow Symfony 7 and test on PHP 8.3

- phpstan-baseline.neon
- src/Bridge/Symfony/DependencyInjection/Configuration.php
- src/Bridge/Symfony/DependencyInjection/ElasticallyExtension.php
- src/Messenger/IndexationRequestHandler.php
- src/Messenger/IndexationRequestSpoolSubscriber.php
> fix(bridge): Make sure the client config option is an array

- composer.json
- src/Bridge/Symfony/DependencyInjection/Configuration.php
- src/Bridge/Symfony/DependencyInjection/ElasticallyExtension.php
- src/IndexBuilder.php
- src/IndexNameMapper.php
- src/Mapping/PhpProvider.php
- src/Mapping/YamlProvider.php
- src/Messenger/IndexationRequest.php
- tests/Symfony/TestKernel.php
Hi @damienalexandre @lyrixx,
I'm getting the following deprecation with SF 7
```
The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "JoliCode\Elastically\Bridge\Symfony\DependencyInjection\ElasticallyExtension".
```
This PR fix it.
> Solve SF 7 deprecation

- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- README.md
- UPGRADE.md
- composer.json
- src/Client.php
- src/Index.php
- src/IndexBuilder.php
- src/Indexer.php
- src/Messenger/IndexationRequestHandler.php
- tests/BaseTestCase.php
- tests/Bridge/Symfony/DependencyInjection/ElasticallyExtensionTest.php
- tests/IndexerTest.php
- tests/Messenger/IndexationRequestHandlerTest.php
Following the merge of Elastica 8, we drop OpenSearch.
Also it's time to remove the deprecated features.
> chore(upgrade): Prepare major version 2 by removing all the dead code

- CHANGELOG.md
- src/Messenger/MultipleIndexationRequest.php
This PR is a fix for https://github.com/jolicode/elastically/issues/197
Before fix
After fix
> Fix deserialize operations objects

- README.md
- UPGRADE.md
- src/Bridge/Symfony/DependencyInjection/Configuration.php
Latests fixes on the documentation.
> chore: prepare version 2.0

- README.md
As per the code, the transport_config option should be placed under the client section, rather than directly at the top level of the connection configuration
**JoliCode\Elastically\Bridge\Symfony\DependencyInjection\ElasticallyExtension**
`````
if ($transportClient = $config['client']['transport_config']['http_client'] ?? null) {
$config['client']['transport_config']['http_client'] = new Reference($transportClient);
}
`````
> fix documentation transport_config
